"""Epidemic population structure simulation package."""

from .contact_matrix import build_contact_matrix, preset_general_cluster
from .interventions import (
    ContactMatrixIntervention,
    InterventionPlan,
    compose_intervention_plan,
    intervene_bridge_links,
    intervene_within_groups,
)
from .model import (
    EpidemicModel,
    GeneralizedStatePoint,
    RK4Stepper,
    ScenarioState,
    StatePoint,
    StateStepper,
    StructuredEpidemicModel,
    StructuredStatePoint,
)
from .parameters import DiseaseParameters, PopulationParameters, SimulationParameters
from .scenarios import Scenario, ScenarioBuilder, get_scenario, list_scenarios
from .notebook_helpers import (
    draw_group_bridge_map,
    effective_matrix,
    get_contact_matrix,
    get_intervention_plan,
    intervention_targets,
    plot_matrix_transformation,
    plot_population_infected_comparison,
    plot_seir_trajectory,
    plot_seirs_trajectory,
    plot_sir_trajectory,
    reload_package_modules,
    run_scenario,
    show_params,
    simulate_seir_euler,
    simulate_seirs_euler,
    simulate_sir_euler,
    summarize_two_population_runs,
    trajectory_to_df,
)

__all__ = [
    "build_contact_matrix",
    "ContactMatrixIntervention",
    "compose_intervention_plan",
    "DiseaseParameters",
    "draw_group_bridge_map",
    "effective_matrix",
    "EpidemicModel",
    "GeneralizedStatePoint",
    "get_contact_matrix",
    "get_intervention_plan",
    "get_scenario",
    "intervention_targets",
    "InterventionPlan",
    "intervene_bridge_links",
    "intervene_within_groups",
    "list_scenarios",
    "plot_matrix_transformation",
    "plot_population_infected_comparison",
    "plot_seir_trajectory",
    "plot_seirs_trajectory",
    "plot_sir_trajectory",
    "PopulationParameters",
    "preset_general_cluster",
    "reload_package_modules",
    "RK4Stepper",
    "run_scenario",
    "Scenario",
    "ScenarioBuilder",
    "ScenarioState",
    "SimulationParameters",
    "StatePoint",
    "StateStepper",
    "StructuredEpidemicModel",
    "StructuredStatePoint",
    "show_params",
    "simulate_seir_euler",
    "simulate_seirs_euler",
    "simulate_sir_euler",
    "summarize_two_population_runs",
    "trajectory_to_df",
]
__version__ = "0.1.0"
